### ISSUE TITLE
Is there video of audreyt's -Ofun talks anywhere?

### ISSUE THREAD

**Issue by g-gundam** [o-fun/o-fun.github.io#2]
Do you know if there is video of any of @audreyt's -Ofun talks anywhere?  I've found [slides](https://speakerdeck.com/audreyt/ofun-optimizing-for-fun), but I'd like to see the talk again if possible.  Thanks in advance.

**Comment by wbraswell** [comment]
I don't see any on the YAPC Youtube channel:
https://www.youtube.com/c/YAPCNA/search?query=tang

**Comment by rurban** [comment]
I don't think so. She was very uncomfortable with videos of her.
